### ISSUE TITLE
MySQL specific functions used in custom SQL queries

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-mod_custommailing#1]
The module relies on MySQL specific SQL functions in its custom queries, e.g.: https://github.com/cbluesprl/moodle-mod_custommailing/blob/01fad19ce7debd64a5bb4276cb0e4b787883f337/lib.php#L337

There is no need for that - the timestamps can be easily calculated at PHP level and the DB should  compare just plain integers.

At the moment, the plugin fails with error on PostgreSQL and likely other databases, too.

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Cross-DB_compatibility

**Comment by mudrd8mz** [comment]
Also for `CONCAT` there is `$DB->sql_concat()` but again - better not to have this at SQL level but instead use standard helpers such as `fullname()` etc. Note there are various settings that affect how and where names are displayed.

https://docs.moodle.org/dev/Data_manipulation_API#sql_concat

**Comment by renaudlemaire** [comment]
Hello David,

Thanks for your time.
Both have been fixed.
