### ISSUE TITLE
The mail is never sent

### ISSUE THREAD

**Issue by ernesto0119** [cbluesprl/moodle-mod_custommailing#10]
Mail never queues, never leaves the server, never reaches the system log table

**Comment by Joaogaspar87** [comment]
I have the same problem, I configured it according to the guidelines and tried all the ways it is only sending to the Moodle administrators and not to the students.

**Comment by realmls** [comment]
I have the same issue no matter what I do the email does not get sent to the end user.

**Comment by Lhannecart** [comment]
Hello,

A patch has been deployed on all branches.

Thank you all for your report.

**Comment by realmls** [comment]
I applied the new update but the email still does not queue or get sent. I am running version 4.1.4.

**Comment by realmls** [comment]
This has not been resolved.
