### ISSUE TITLE
"At Course Enrol" checkbox not working.

### ISSUE THREAD

**Issue by heinrichplutolms** [cbluesprl/moodle-mod_custommailing#9]
When selecting the "At Course Enrol" checkbox it is being selected but when you submit it does not set and when you go back in to edit the activity it is no longer selected.

**Comment by Fleoxi** [comment]
Hello,

The problem is fixed and uploaded on Moodle Plugins.

Julien

**Comment by realmls** [comment]
I have the same issue even after I applied the latest update.
